I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 32, in script
    m "It's a kind of videogame you can play on your computer or a console."
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 32, in script
    m "It's a kind of videogame you can play on your computer or a console."
  File "/Users/brad/Development/bdf_code/renpy-7.3.5-sdk/renpy/ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/brad/Development/bdf_code/renpy-7.3.5-sdk/renpy/ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Darwin-18.5.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
test 1.0
Thu Apr 16 12:49:06 2020
